version: '3.7'
services:
  ignite-api:
    build:
      context: .
      dockerfile: backend.docker
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - ${API_PORT}:3001
    volumes:
      - /app/node_modules
